### ISSUE TITLE
jsonb containment operators not supported, how to implement properly?

### ISSUE THREAD

**Issue by mauritslamers** [Suor/sql-bricks-postgres#5]
I am trying to use sql-bricks-postgres (through pg-bricks) to create queries containing where clauses with jsonb containment operators. I noticed these are not supported in sql-bricks-postgres.

Diving into this it turns out sql-bricks itself is written in such a way that the base prototypes for these infix operators are not exposed. To me the only way to add new operators seems to be to create an existing operator (such as eq or equal) and then changing the operator property:

```
var sql = require('sql-bricks-postgres');
sql.jsonb_contains = function (col, val) {
  var lt = sql.lt(col, val);
  lt.op = "@>";
  return lt;
};

sql.select().where(sql.jsonb_contains('field', { key: 'value' }))
```

While this "hack" returns correct SQL queries, do you know whether there are more appropriate  methods for adding operators?

**Comment by Suor** [comment]
You'll probably need to go to `sql-bricks` and suggest making `Binary` public. Then you'll be able to inherit from that.

**Comment by prust** [comment]
Thanks for the direction @Suor. I made Binary public in https://github.com/CSNW/sql-bricks/pull/71.

**Comment by Suor** [comment]
Looks like it's inpractical to implement all the postgresql operators, so [this utility](https://github.com/CSNW/sql-bricks/issues/74) will be a way to go once implemented.

**Comment by Suor** [comment]
Not going to implement it, postgres has too many operators. The official way of doing such stuff is using `sql()` with params:
```js
sql.select().where(sql('field @> $', 'value'))
```

**Comment by Pholey** [comment]
> Not going to implement it, postgres has too many operators. The official way of doing such stuff is using sql() with params...

I don't think this is the proper mindset to have.. Isn't support like this the very purpose of this library? Sure we can use sql(), but we could use sql() in plain ol sql-bricks too as well.. Even after the wrapper around the main Postgres operators, there are still _tons_ of edge cases I deal with on a daily basis that require me to switch from using the sqlbricks API to raw sql mangling, which in turn causes me to lose things like automatic escaping & dynamic query building.. It's really quite a PIA to the point of where I commonly patch this library rather than dealing with it

**Comment by Suor** [comment]
I can't see how 
```js
sql.select().where(sql.jsonb_contains('field', { key: 'value' }))
```
is better then 
```js
sql.select().where(sql('field @> $', { key: 'value' }))
```

1. It's longer.
2. Harder to use - one must know how all those ops are called in `sql-bricks-postgres`.
3. Harder to implement.

I don't see any edge cases here that `sql.op()` solves.
